kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sadc-privileged
  labels:
    app: sadc-collector
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
