apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sadc-collector
  namespace: node-performance-monitoring
spec:
  selector:
    matchLabels:
      app: sadc-collector
  template:
    metadata:
      labels:
        app: sadc-collector
    spec:
      restartPolicy: Always
      serviceAccountName: sadc-collector
      hostPID: true
      hostNetwork: true
      enableServiceLinks: true
      securityContext: {}
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchFields:
            - key: metadata.name
              operator: In
              values:
              - target-host-name
      containers:
        - name: sadc-container
          env:
            - name: sadc_frequency
              value: "10m"
          command:
            - /usr/bin/bash
          args: 
            - '-c'
            - /var/sadc/collect
          securityContext:
            privileged: true
            runAsUser: 0
          imagePullPolicy: Always
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: collector-script
              readOnly: true
              mountPath: /var/sadc/
          image: quay.io/bjarvis/sadc-container:8.5
      serviceAccount: sadc-container
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
        - name: collector-script
          configMap:
            name: collector-script
            defaultMode: 511
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: Exists
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  revisionHistoryLimit: 5
